(()=>{
const $=id=>document.getElementById(id),status=t=>{if($('status'))$('status').textContent=t};
const css=document.createElement('style');css.textContent='.key{touch-action:none;-webkit-user-select:none;user-select:none}.labCard{margin-top:14px}.labGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:10px}.labGrid label{display:flex;flex-direction:column;gap:5px}.labRow{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.labSelect{min-width:145px}.padGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.pad{min-height:78px;font-weight:800}.pad small{display:block;opacity:.65}.pad.on{transform:scale(.97);outline:2px solid currentColor}.meter{height:7px;border-radius:8px;background:currentColor;opacity:.25;overflow:hidden}.meter i{display:block;height:100%;width:0%;background:currentColor;opacity:1}.pitchReadout{font-size:.9rem;font-weight:700}';document.head.appendChild(css);
let voices=new Map();
async function audio(){let a=window.__instrumentLabAudio,ctx=a?.context;if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});try{if(ctx.state!=='running')await ctx.resume()}catch(e){}return{ctx,master:a?.master||ctx.destination}}
const hz=m=>440*Math.pow(2,(m-69)/12);
const keyMap=[['A',60],['W',61],['S',62],['E',63],['D',64],['F',65],['T',66],['G',67],['Y',68],['H',69],['U',70],['J',71],['K',72]];
async function noteOn(n){if(voices.has(n))return;let x=await audio(),base=keyMap.find(k=>k[0]===n)?.[1]??60,oct=+$('octave')?.textContent||0,m=base+oct*12,o=x.ctx.createOscillator(),g=x.ctx.createGain();o.type=$('wave')?.value||'sawtooth';o.frequency.value=hz(m);let t=x.ctx.currentTime;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.025,Math.min(.35,(+$('volume')?.value||.5)*.5)),t+Math.max(.003,+$('attack')?.value||.02));o.connect(g);g.connect(x.master);o.start();voices.set(n,{o,g,ctx:x.ctx});document.querySelector(`[data-key="${n}"]`)?.classList.add('down')}
function noteOff(n){let v=voices.get(n);if(!v)return;let t=v.ctx.currentTime,r=Math.max(.02,+$('release')?.value||.15);try{v.g.gain.cancelScheduledValues(t);v.g.gain.setValueAtTime(Math.max(.0001,v.g.gain.value),t);v.g.gain.exponentialRampToValueAtTime(.0001,t+r);v.o.stop(t+r+.03)}catch(e){}voices.delete(n);document.querySelector(`[data-key="${n}"]`)?.classList.remove('down')}
document.querySelectorAll('.key').forEach(b=>{let n=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopImmediatePropagation();b.setPointerCapture?.(e.pointerId);noteOn(n)},{capture:true,passive:false});b.addEventListener('pointerup',e=>{e.preventDefault();e.stopImmediatePropagation();noteOff(n)},{capture:true,passive:false});b.addEventListener('pointercancel',()=>noteOff(n),{capture:true});b.addEventListener('lostpointercapture',()=>noteOff(n),{capture:true});b.addEventListener('touchstart',e=>{e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false})});
const unlock=document.createElement('button');unlock.textContent='🔊 Enable iPhone Audio';unlock.type='button';unlock.onclick=async()=>{await audio();unlock.textContent='✓ iPhone Audio Ready';status('iPhone audio ready')};$('audioStart')?.after(unlock);

// Universal local media intake
const file=$('file'),box=$('visualizerBox');if(file){file.accept='*/*';file.addEventListener('change',()=>{let f=file.files?.[0];if(f)status(`Loaded ${f.name} · ${f.type||'unknown format'}`)})}if(box){box.addEventListener('dragover',e=>{e.preventDefault();box.classList.add('dropReady')});box.addEventListener('dragleave',()=>box.classList.remove('dropReady'));box.addEventListener('drop',e=>{e.preventDefault();box.classList.remove('dropReady');let f=e.dataTransfer?.files?.[0];if(!f){return}if(file){let d=new DataTransfer();d.items.add(f);file.files=d.files;file.dispatchEvent(new Event('change',{bubbles:true}))}})}

// DJ sampler: 16 pads, per-pad volume/mute/loop, file loading, recording.
const viz=$('visualizer');if(viz){let card=document.createElement('div');card.className='card labCard';card.innerHTML=`<div class="sectionTitle">🎛 DJ SOUND LAB</div><div class="labRow"><button id="djRec">● Record</button><button id="djStop" disabled>■ Stop</button><button id="djLoad">＋ Load Sample</button><input id="djFile" type="file" accept="audio/*,video/*" hidden><button id="djAllStop">■ All Stop</button><button id="djClear">Clear</button></div><div class="labGrid"><label>Pad Volume<input id="padVol" type="range" min="0" max="1" step=".01" value=".8"><output id="padVolOut">80%</output></label><label>Master Deck<input id="deckMaster" type="range" min="0" max="1" step=".01" value=".9"><output id="deckMasterOut">90%</output></label></div><div id="pads" class="padGrid"></div><div class="hint">Tap a pad to play. Tap again to retrigger. Each pad has Mute and Loop controls.</div>`;viz.parentNode.insertBefore(card,viz);let pads=$('pads'),data=Array.from({length:16},()=>({url:null,name:'Empty',loop:false,muted:false,audios:[]}));
function makePad(i){let p=document.createElement('div');p.className='padWrap';p.innerHTML=`<button class="pad" id="pad${i}">${i+1}. Empty<small>Tap to play</small></button><div class="labRow"><button data-m="${i}">M</button><button data-l="${i}">Loop</button></div>`;pads.appendChild(p);let b=$('pad'+i);b.onclick=()=>{let d=data[i];if(!d.url){status(`Pad ${i+1} is empty`);return}let a=new Audio(d.url);a.volume=d.muted?0:+$('padVol').value*+$('deckMaster').value;a.loop=d.loop;d.audios.push(a);b.classList.add('on');a.onended=()=>b.classList.remove('on');a.play().catch(()=>status('Playback blocked · tap Enable iPhone Audio first'))};p.querySelector(`[data-m="${i}"]`).onclick=()=>{data[i].muted=!data[i].muted;p.querySelector(`[data-m="${i}"]`).textContent=data[i].muted?'Unmute':'M';};p.querySelector(`[data-l="${i}"]`).onclick=()=>{data[i].loop=!data[i].loop;p.querySelector(`[data-l="${i}"]`).textContent=data[i].loop?'Loop ✓':'Loop'};return b}for(let i=0;i<16;i++)makePad(i);
function loadBlob(blob,name,i){if(data[i].url)URL.revokeObjectURL(data[i].url);data[i].url=URL.createObjectURL(blob);data[i].name=name;$('pad'+i).innerHTML=`${i+1}. ${name.slice(0,18)}<small>Tap to play</small>`;status(`Loaded pad ${i+1}: ${name}`)}
$('djLoad').onclick=()=>{$('djFile').click()};$('djFile').onchange=e=>{let f=e.target.files?.[0];if(f){let i=data.findIndex(d=>!d.url);loadBlob(f,f.name,i<0?0:i)}};$('padVol').oninput=e=>$('padVolOut').textContent=Math.round(e.target.value*100)+'%';$('deckMaster').oninput=e=>$('deckMasterOut').textContent=Math.round(e.target.value*100)+'%';$('djAllStop').onclick=()=>data.forEach(d=>d.audios.splice(0).forEach(a=>{a.pause();a.currentTime=0}));$('djClear').onclick=()=>data.forEach((d,i)=>{if(d.url)URL.revokeObjectURL(d.url);d.url=null;d.name='Empty';d.audios=[];d.loop=false;d.muted=false;$('pad'+i).innerHTML=`${i+1}. Empty<small>Tap to play</small>`});
let rec=null,chunks=[];$('djRec').onclick=async()=>{try{let s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false}});chunks=[];rec=new MediaRecorder(s);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{s.getTracks().forEach(t=>t.stop());let b=new Blob(chunks,{type:rec.mimeType||'audio/webm'});loadBlob(b,'Mic Take',data.findIndex(d=>!d.url)<0?0:data.findIndex(d=>!d.url));$('djRec').disabled=false;$('djStop').disabled=true;status('Recording saved to a DJ pad')};rec.start(100);$('djRec').disabled=true;$('djStop').disabled=false;status('Recording…')}catch(e){status('Microphone permission/recording unavailable')}};$('djStop').onclick=()=>{if(rec?.state==='recording')rec.stop()};}

// Vocal pitch lab: real-time pitch detection + note snapping guidance, with correction controls kept separate from FX.
const vocal=document.createElement('div');vocal.className='card labCard';vocal.innerHTML=`<div class="sectionTitle">🎙 VOCAL PITCH LAB</div><div class="labRow"><button id="pitchStart">Start Pitch Monitor</button><button id="pitchStop" disabled>Stop</button><label>Auto-Tune <input id="pitchOn" type="checkbox"></label></div><div class="labGrid"><label>Correction<input id="pitchAmt" type="range" min="0" max="1" step=".01" value=".75"><output id="pitchAmtOut">75%</output></label><label>Retune Speed<input id="retune" type="range" min="0" max="1" step=".01" value=".7"><output id="retuneOut">70%</output></label><label>Key<select id="pitchKey" class="labSelect"><option>C</option><option>C#</option><option>D</option><option>D#</option><option>E</option><option>F</option><option>F#</option><option>G</option><option>G#</option><option>A</option><option>A#</option><option>B</option></select></label><label>Scale<select id="pitchScale" class="labSelect"><option>chromatic</option><option>major</option><option>minor</option></select></label></div><div class="pitchReadout" id="pitchReadout">Pitch: — · Target: —</div><div class="meter"><i id="pitchMeter"></i></div><div class="hint">The monitor detects the sung fundamental and calculates the nearest target note. The Auto-Tune controls are ready for a dedicated pitch-shifting processor; this version deliberately does not mislabel simple EQ/filtering as pitch correction.</div>`;document.querySelector('main')?.appendChild(vocal);
let ps=null,an=null,raf=0;function detect(buf,sr){let rms=0;for(let i=0;i<buf.length;i++)rms+=buf[i]*buf[i];rms=Math.sqrt(rms/buf.length);if(rms<.012)return null;let best=0,bestC=0;for(let lag=20;lag<Math.min(1000,buf.length/2);lag++){let c=0;for(let i=0;i<buf.length-lag;i++)c+=buf[i]*buf[i+lag];if(c>bestC){bestC=c;best=lag}}return best?sr/best:null}
function pitchLoop(){if(!an)return;let b=new Float32Array(an.fftSize);an.getFloatTimeDomainData(b);let f=detect(b,an.context.sampleRate);if(f){let midi=69+12*Math.log2(f/440),note=Math.round(midi),names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],name=names[(note+120)%12];let key=$('pitchKey').value,scale=$('pitchScale').value;let allowed=names;if(scale!=='chromatic'){let root=names.indexOf(key),steps=scale==='major'?[0,2,4,5,7,9,11]:[0,2,3,5,7,8,10];allowed=steps.map(s=>names[(root+s)%12])}let target=allowed.reduce((best,n)=>{let d=Math.abs(((names.indexOf(n)-names.indexOf(name)+6)%12)-6);return d<best.d?{n,d}:best},{n:name,d:99}).n;$('pitchReadout').textContent=`Pitch: ${f.toFixed(1)} Hz · ${name} · Target: ${target}`;$('pitchMeter').style.width=Math.min(100,Math.max(3,(rmsLevel(b)*400)))+'%'}raf=requestAnimationFrame(pitchLoop)}function rmsLevel(b){let r=0;for(let x of b)r+=x*x;return Math.sqrt(r/b.length)}
$('pitchStart').onclick=async()=>{try{let s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});let x=await audio();ps=s;an=x.ctx.createAnalyser();an.fftSize=2048;let src=x.ctx.createMediaStreamSource(s);src.connect(an);$('pitchStart').disabled=true;$('pitchStop').disabled=false;pitchLoop();status('Pitch monitor running')}catch(e){status('Microphone permission denied')}};$('pitchStop').onclick=()=>{ps?.getTracks().forEach(t=>t.stop());ps=null;an=null;cancelAnimationFrame(raf);$('pitchStart').disabled=false;$('pitchStop').disabled=true;status('Pitch monitor stopped')};$('pitchAmt').oninput=e=>$('pitchAmtOut').textContent=Math.round(e.target.value*100)+'%';$('retune').oninput=e=>$('retuneOut').textContent=Math.round(e.target.value*100)+'%';

// Bluetooth/system output routing. iOS decides the final route when Safari cannot set a sink directly.
const out=document.createElement('div');out.className='card labCard';out.innerHTML=`<div class="sectionTitle">🎧 OUTPUT ROUTING</div><button id="btOut">Bluetooth / AirPlay Output</button><div class="hint">On iPhone: connect AirPods/Bluetooth speaker, then select it from Control Center → AirPlay. Safari normally follows the iOS route. Some desktop browsers also expose a per-device selector.</div>`;document.querySelector('main')?.appendChild(out);$('btOut').onclick=async()=>{await audio();status('Connect/select Bluetooth or AirPlay from iPhone Control Center')};
addEventListener('blur',()=>voices.forEach((_,k)=>noteOff(k)));addEventListener('beforeunload',()=>voices.forEach((_,k)=>noteOff(k)));
})();