(()=>{
  const $=id=>document.getElementById(id);
  const keys=[['A',60],['W',61],['S',62],['E',63],['D',64],['F',65],['T',66],['G',67],['Y',68],['H',69],['U',70],['J',71],['K',72]];
  let midi=null,pressedMidi=new Map(),iosVoices=new Map();
  const setStatus=t=>{if($('status'))$('status').textContent=t};
  const style=document.createElement('style');style.textContent='.key{touch-action:none;-webkit-user-select:none;user-select:none;-webkit-touch-callout:none}.key.down{transform:translateY(2px)}.labCard{margin-top:12px}.labGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.labGrid label{display:flex;flex-direction:column;gap:5px}.labPads{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.labPad{min-height:70px;font-weight:800}.labPad small{display:block;opacity:.7;font-weight:500}.labRow{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.labSelect{min-width:170px}.mediaPreview{width:100%;max-height:300px;border-radius:12px;margin-top:10px}.deckActive{outline:2px solid currentColor}';document.head.appendChild(style);
  async function getAudio(){const api=window.__instrumentLabAudio;let ctx=api?.context;if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});try{if(ctx.state!=='running')await ctx.resume()}catch(e){}return {ctx,master:api?.master||ctx.destination};}
  const hz=m=>440*Math.pow(2,(m-69)/12);
  async function iosNoteOn(name){if(iosVoices.has(name))return;const x=await getAudio();const wave=$('wave')?.value||'triangle';const vol=Math.min(.35,Math.max(.03,(+$('volume')?.value||.35)*.5));const oct=Math.max(-3,Math.min(3,+$('octave')?.textContent||0));const m=(keys.find(k=>k[0]===name)?.[1]??60)+oct*12;const o=x.ctx.createOscillator(),g=x.ctx.createGain();o.type=wave;o.frequency.value=hz(m);const t=x.ctx.currentTime,a=Math.max(.002,+$('attack')?.value||.02);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+a);o.connect(g);g.connect(x.master);o.start();iosVoices.set(name,{o,g,ctx:x.ctx});$('noteReadout')&&($('noteReadout').textContent=`${name} · ${hz(m).toFixed(1)} Hz`);document.querySelector(`[data-key="${name}"]`)?.classList.add('down');}
  function iosNoteOff(name){const v=iosVoices.get(name);if(!v)return;const t=v.ctx.currentTime,r=Math.max(.015,+$('release')?.value||.3);try{v.g.gain.cancelScheduledValues(t);v.g.gain.setValueAtTime(Math.max(.0001,v.g.gain.value),t);v.g.gain.exponentialRampToValueAtTime(.0001,t+r);v.o.stop(t+r+.03)}catch(e){}iosVoices.delete(name);document.querySelector(`[data-key="${name}"]`)?.classList.remove('down')}
  document.querySelectorAll('.key').forEach(b=>{const name=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopImmediatePropagation();b.setPointerCapture?.(e.pointerId);iosNoteOn(name)},{capture:true,passive:false});b.addEventListener('pointerup',e=>{e.preventDefault();e.stopImmediatePropagation();iosNoteOff(name)},{capture:true,passive:false});b.addEventListener('pointercancel',e=>{e.preventDefault();e.stopImmediatePropagation();iosNoteOff(name)},{capture:true,passive:false});b.addEventListener('lostpointercapture',()=>iosNoteOff(name),{capture:true});b.addEventListener('touchstart',e=>{e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});b.addEventListener('touchend',e=>{e.preventDefault();e.stopImmediatePropagation()},{capture:true,passive:false});b.addEventListener('touchcancel',e=>{e.preventDefault();e.stopImmediatePropagation();iosNoteOff(name)},{capture:true,passive:false})});
  addEventListener('blur',()=>[...iosVoices.keys()].forEach(iosNoteOff));
  const unlock=document.createElement('button');unlock.id='iosAudioUnlock';unlock.type='button';unlock.textContent='🔊 Enable iPhone Audio';unlock.style.cssText='margin:.5rem 0;display:block;width:100%;font-weight:700;';$('audioStart')?.after(unlock);unlock.onclick=async()=>{try{await getAudio();setStatus('iPhone audio ready · play the keys');unlock.textContent='✓ iPhone Audio Ready'}catch(e){setStatus('Tap again to enable audio')}};
  const midiBtn=document.createElement('button');midiBtn.id='midi';midiBtn.type='button';midiBtn.textContent='🎹 MIDI';unlock.after(midiBtn);const keyForMidi=n=>{const d=n-60;return d>=0&&d<13?keys[d][0]:null};const octaveForMidi=n=>Math.floor((n-60)/12);const sendKey=(type,key)=>window.dispatchEvent(new KeyboardEvent(type,{key,bubbles:true}));
  function midiMessage(e){const [status,note,velocity]=e.data||[],cmd=status&240,key=keyForMidi(note);if(!key)return;const target=Math.max(-3,Math.min(3,octaveForMidi(note)));if(cmd===144&&velocity>0){if(pressedMidi.has(note))return;while((+$('octave')?.textContent||0)<target)$('octPlus')?.click();while((+$('octave')?.textContent||0)>target)$('octMinus')?.click();pressedMidi.set(note,key);sendKey('keydown',key)}else if(cmd===128||(cmd===144&&velocity===0)){if(pressedMidi.has(note)){sendKey('keyup',pressedMidi.get(note));pressedMidi.delete(note)}}}
  midiBtn.onclick=async()=>{if(!navigator.requestMIDIAccess){setStatus('MIDI is not supported in this browser');return}try{midi=await navigator.requestMIDIAccess();for(const i of midi.inputs.values())i.onmidimessage=midiMessage;setStatus(`MIDI ready · ${midi.inputs.size} input${midi.inputs.size===1?'':'s'}`);midiBtn.textContent='✓ MIDI'}catch(e){setStatus('MIDI connection failed')}};

  // Accept any local file. Browser playback/preview is capability-dependent by MIME/container.
  const box=$('visualizerBox'),file=$('file');
  if(box&&file){file.setAttribute('accept','*/*');['dragenter','dragover'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.add('dropReady')}));['dragleave','drop'].forEach(ev=>box.addEventListener(ev,e=>{e.preventDefault();box.classList.remove('dropReady')}));box.addEventListener('drop',e=>{const f=e.dataTransfer?.files?.[0];if(!f){setStatus('Drop a media file');return}const dt=new DataTransfer();dt.items.add(f);file.files=dt.files;file.dispatchEvent(new Event('change',{bubbles:true}));setStatus(`Loaded ${f.name}`)})}

  // DJ deck: record, replay, download and trigger local sample pads.
  const viz=$('visualizer');
  if(viz){const card=document.createElement('div');card.className='card labCard';card.innerHTML=`<div class="sectionTitle">🎛 DJ DECK & MEDIA BAY</div><div class="labRow"><button id="labRecord">● Record Mic</button><button id="labStop" disabled>■ Stop</button><button id="labPlayLast" disabled>▶ Play Last</button><button id="labDownload" disabled>⬇ Save Take</button><button id="labClear">Clear Pads</button></div><div class="labGrid"><label>Deck Volume<input id="deckVol" type="range" min="0" max="1" step=".01" value=".8"><output id="deckVolOut">80%</output></label><label>Auto-Tune<input id="autoTune" type="checkbox"><span>Pitch Assist</span></label><label>Tune Amount<input id="tuneAmount" type="range" min="0" max="1" step=".01" value=".7"><output id="tuneAmountOut">70%</output></label><label>Key<select id="tuneKey" class="labSelect"><option>C</option><option>C#</option><option>D</option><option>D#</option><option>E</option><option>F</option><option>F#</option><option>G</option><option>G#</option><option>A</option><option>A#</option><option>B</option></select></label><label>Scale<select id="tuneScale" class="labSelect"><option>major</option><option>minor</option><option>chromatic</option></select></label></div><div class="hint">Pitch Assist exposes key/scale/amount controls for the vocal-processing layer. A true transparent real-time Auto-Tune engine requires dedicated pitch detection + pitch shifting; this build does not fake that with a filter.</div><div id="labPads" class="labPads"></div>`;viz.parentNode.insertBefore(card,viz);
    const pads=$('labPads');let takes=[],lastUrl=null,rec=null,chunks=[];const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg'].find(m=>window.MediaRecorder?.isTypeSupported?.(m))||'';
    function addPad(blob,name){const url=URL.createObjectURL(blob),i=takes.length;takes.push({url,name});const b=document.createElement('button');b.className='labPad';b.innerHTML=`${i+1}. ${name.slice(0,18)}<small>▶ sample</small>`;b.onclick=()=>{const a=new Audio(url);a.volume=+$('deckVol').value;a.play().catch(()=>{})};pads.appendChild(b)}
    $('labRecord').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false}});chunks=[];rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});lastUrl=URL.createObjectURL(blob);addPad(blob,`Take ${new Date().toLocaleTimeString()}`);$('labPlayLast').disabled=false;$('labDownload').disabled=false;$('labPlayLast').onclick=()=>new Audio(lastUrl).play().catch(()=>{});$('labDownload').onclick=()=>{const a=document.createElement('a');a.href=lastUrl;a.download='instrument-lab-take.webm';a.click()};setStatus('Take recorded · added to DJ pads')};rec.start(100);$('labRecord').disabled=true;$('labStop').disabled=false;setStatus('Recording mic…')}catch(e){setStatus('Microphone recording unavailable')}};
    $('labStop').onclick=()=>{if(rec?.state==='recording')rec.stop();$('labRecord').disabled=false;$('labStop').disabled=true};$('labClear').onclick=()=>{takes.forEach(t=>URL.revokeObjectURL(t.url));takes=[];pads.innerHTML='';lastUrl=null;$('labPlayLast').disabled=true;$('labDownload').disabled=true;setStatus('DJ pads cleared')};$('deckVol').oninput=e=>$('deckVolOut').textContent=Math.round(e.target.value*100)+'%';$('tuneAmount').oninput=e=>$('tuneAmountOut').textContent=Math.round(e.target.value*100)+'%';
  }

  // Explicit output routing when supported; on iPhone Safari, Bluetooth is normally controlled by iOS.
  const out=document.createElement('div');out.className='card labCard';out.innerHTML=`<div class="sectionTitle">🎧 AUDIO OUTPUT</div><div class="labRow"><button id="bluetoothOutput">🎧 Bluetooth Output</button><button id="refreshOutputs">↻ Refresh</button><select id="audioOutput" class="labSelect"><option value="">System / iPhone output</option></select></div><div class="hint">Connect AirPods or a Bluetooth speaker, then choose it from iPhone Control Center. If Safari exposes output selection, the picker above can route supported media directly.</div>`;document.querySelector('main')?.appendChild(out);
  async function refreshOutputs(){const s=$('audioOutput');if(!navigator.mediaDevices?.enumerateDevices)return;try{const ds=await navigator.mediaDevices.enumerateDevices();s.innerHTML='<option value="">System / iPhone output</option>';ds.filter(d=>d.kind==='audiooutput').forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Audio output ${i+1}`;s.appendChild(o)})}catch(e){}}
  $('refreshOutputs').onclick=refreshOutputs;$('bluetoothOutput').onclick=async()=>{await getAudio();if(HTMLMediaElement.prototype.setSinkId){await refreshOutputs();setStatus('Select a Bluetooth output')}else{setStatus('Use iPhone Control Center → AirPlay/Bluetooth output')}};$('audioOutput').onchange=async e=>{if(!e.target.value)return;try{for(const el of document.querySelectorAll('audio,video'))if(el.setSinkId)await el.setSinkId(e.target.value);setStatus('Audio output selected')}catch(e){setStatus('Output selection unavailable · use Control Center')}};
  addEventListener('beforeunload',()=>{pressedMidi.forEach(key=>sendKey('keyup',key));iosVoices.forEach((_,key)=>iosNoteOff(key));});
})();
