(()=>{
const $=id=>document.getElementById(id);
let micStream=null,micSource=null,micChain=null,monitorGain=null,vizAnalyser=null,renderCanvas=null,renderCtx=null;
function shared(){return window.__instrumentLabAudio||{}}
async function getAudio(){const a=shared();if(!a.context)return null;try{if(a.context.state!=='running')await a.context.resume()}catch(e){}return a}
function ensureViz(){const a=shared();if(!a.context||!a.master)return null;if(!vizAnalyser){vizAnalyser=a.context.createAnalyser();vizAnalyser.fftSize=2048;vizAnalyser.smoothingTimeConstant=.78;a.master.connect(vizAnalyser);const mute=a.context.createGain();mute.gain.value=0;vizAnalyser.connect(mute);mute.connect(a.context.destination)}if(!renderCanvas){const box=$('visualizerBox');if(!box)return null;renderCanvas=document.createElement('canvas');renderCanvas.id='vizOverlay';renderCanvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:2';box.style.position='relative';box.appendChild(renderCanvas);renderCtx=renderCanvas.getContext('2d');const resize=()=>{const r=box.getBoundingClientRect(),d=devicePixelRatio||1;renderCanvas.width=Math.max(1,r.width*d);renderCanvas.height=Math.max(1,r.height*d);renderCtx.setTransform(d,0,0,d,0,0)};addEventListener('resize',resize);resize();const draw=()=>{requestAnimationFrame(draw);const w=box.clientWidth,h=box.clientHeight;if(!w||!h||!vizAnalyser)return;const data=new Uint8Array(vizAnalyser.frequencyBinCount);vizAnalyser.getByteFrequencyData(data);renderCtx.clearRect(0,0,w,h);const sens=+$('sensitivity').value,mode=$('vizMode').value,theme=$('theme').value,col={pink:'#d946ef',cyan:'#22d3ee',fire:'#fb923c',mono:'#fff'}[theme]||'#d946ef';renderCtx.fillStyle=col;renderCtx.strokeStyle=col;renderCtx.shadowBlur=10;renderCtx.shadowColor=col;if(mode==='bars'){const n=Math.max(1,Math.min(96,Math.floor(w/7))),bw=w/n;for(let i=0;i<n;i++){const val=Math.min(1,data[Math.floor(i*data.length/n)]/255*sens),hh=val*h*.9;renderCtx.fillRect(i*bw+1,h-hh,Math.max(1,bw-3),hh)}}else if(mode==='circular'){const cx=w/2,cy=h/2,base=Math.min(w,h)*.18;renderCtx.beginPath();renderCtx.arc(cx,cy,base,0,Math.PI*2);renderCtx.stroke();for(let i=0;i<120;i++){const val=data[Math.floor(i*data.length/120)]/255*sens,ang=i*Math.PI*2/120,r=base+val*Math.min(w,h)*.32;renderCtx.beginPath();renderCtx.moveTo(cx+Math.cos(ang)*base,cy+Math.sin(ang)*base);renderCtx.lineTo(cx+Math.cos(ang)*r,cy+Math.sin(ang)*r);renderCtx.stroke()}}else{renderCtx.beginPath();for(let i=0;i<700;i++){const val=data[Math.floor(i*data.length/700)]/255,y=h/2+(val-.5)*h*.85*sens,x=i/700*w;i?renderCtx.lineTo(x,y):renderCtx.moveTo(x,y)}renderCtx.stroke()}renderCtx.shadowBlur=0};draw()}return vizAnalyser}
async function startMic(){const a=await getAudio();if(!a)return;ensureViz();try{if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1}});micSource=a.context.createMediaStreamSource(micStream);let n=micSource;const g=a.context.createGain();g.gain.value=+$('micGain').value;n.connect(g);n=g;if($('micCompressor').checked){const c=a.context.createDynamicsCompressor();c.threshold.value=-20;c.knee.value=20;c.ratio.value=5;c.attack.value=.003;c.release.value=.12;n.connect(c);n=c}if($('autoTube').checked){const ws=a.context.createWaveShaper(),amt=+$('tubeDrive').value,k=1+amt*18,curve=new Float32Array(1024);for(let i=0;i<curve.length;i++){const x=i*2/curve.length-1;curve[i]=(1+k)*x/(1+k*Math.abs(x))}ws.curve=curve;ws.oversample='2x';n.connect(ws);n=ws}if($('micRadio').checked){const f=a.context.createBiquadFilter();f.type='bandpass';f.frequency.value=1500;f.Q.value=.7;n.connect(f);n=f}if($('micMegaphone').checked){const f=a.context.createBiquadFilter();f.type='peaking';f.frequency.value=1800;f.Q.value=1.2;f.gain.value=10;n.connect(f);n=f}micChain=n;n.connect(vizAnalyser);monitorGain=a.context.createGain();monitorGain.gain.value=$('micMonitor').checked?1:0;n.connect(monitorGain);monitorGain.connect(a.master);$('fileName').textContent='Microphone input active';$('mic').textContent='🎙 Mic Active';$('status').textContent='Microphone active · visualization live'}catch(e){$('status').textContent=e?.name==='NotAllowedError'?'Microphone permission blocked':'Microphone could not start'}}
function stopMic(){if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;try{micSource?.disconnect()}catch(e){}try{micChain?.disconnect()}catch(e){}try{monitorGain?.disconnect()}catch(e){}micSource=null;micChain=null;monitorGain=null;$('mic').textContent='🎙 Microphone';$('status').textContent='Microphone off'}
$('mic').onclick=e=>{e.preventDefault();e.stopImmediatePropagation();startMic()};$('micStop').onclick=e=>{e.preventDefault();e.stopImmediatePropagation();stopMic()};$('micMonitor')?.addEventListener('change',()=>{if(monitorGain)monitorGain.gain.value=$('micMonitor').checked?1:0});ensureViz();
})();